class Failure implements Exception {

  Failure([this.message = 'Ocurri√≥ un error inesperado']);

  final String message;
}
